apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-pipeline-system
  labels:
    app: ci-cd-pipeline-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-cd-pipeline-system
  template:
    metadata:
      labels:
        app: ci-cd-pipeline-system
    spec:
      containers:
      - name: ci-cd-pipeline-system
        image: atharavlokhande99/ci-cd-pipeline-system:latest
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: APP_VERSION
          value: "1.0.0"
